Repository vancluever/terraform-provider-acme, pull requests merged in 2019-05, with the labels that each got.

#42 handle revoked certificates better
  acme/acme_structure.go
  acme/resource_acme_certificate.go
Labels: size/XS

#46 r/registration: fix error message pattern in test destroy check
  acme/resource_acme_registration_test.go
Labels: size/XS

#48 r/certificate: adjust min_days_remaining default to 30
  acme/acme_migrations_test.go
  acme/acme_structure.go
  website/docs/r/certificate.html.markdown
Labels: documentation, size/XS

#49 Add challenge support for multiple DNS providers
  acme/acme_migrations.go
  acme/acme_migrations_test.go
  acme/acme_structure.go
  acme/acme_structure_test.go
  acme/resource_acme_certificate.go
  acme/resource_acme_certificate_test.go
  go.mod
  website/docs/dns_providers/index.html.markdown
  website/docs/r/certificate.html.markdown
Labels: documentation, size/XL

#53 plugin: log lego's log messages in Terraform
  logger.go
  main.go
Labels: size/S

#55 acme: fix migration to schema version 4 (TF 0.11)
  acme/acme_migrations.go
  acme/acme_migrations_test.go
Labels: size/M

#57 acme: decouple and version current resource schemas
  acme/acme_structure.go
  acme/acme_structure_test.go
  acme/resource_acme_certificate.go
  acme/resource_acme_registration.go
  acme/resource_acme_registration_test.go
Labels: size/XL

#56 acme: add TF 0.12 state upgrader for V3 -> V4
  acme/acme_migrations.go
  acme/acme_migrations_011.go
  acme/acme_migrations_011_test.go
  acme/acme_migrations_test.go
  acme/resource_acme_certificate.go
  go.mod
  vendor/modules.txt
Labels: dependencies, size/XL

#58 modules: upgrade Terraform to v0.12.0
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-getter/README.md
  vendor/github.com/hashicorp/go-getter/decompress_zip.go
  vendor/github.com/hashicorp/go-getter/get_git.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.rl
  vendor/github.com/hashicorp/hcl2/hclwrite/format.go
  vendor/github.com/hashicorp/terraform/addrs/resourcemode_string.go
  vendor/github.com/hashicorp/terraform/config/resource_mode_string.go
  vendor/github.com/hashicorp/terraform/configs/provisioneronfailure_string.go
  vendor/github.com/hashicorp/terraform/configs/provisionerwhen_string.go
  vendor/github.com/hashicorp/terraform/configs/variabletypehint_string.go
  vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go
  vendor/github.com/hashicorp/terraform/helper/schema/core_schema.go
  vendor/github.com/hashicorp/terraform/helper/schema/getsource_string.go
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform/helper/schema/shims.go
  vendor/github.com/hashicorp/terraform/helper/schema/valuetype_string.go
  vendor/github.com/hashicorp/terraform/internal/initwd/module_install.go
  vendor/github.com/hashicorp/terraform/lang/funcs/collection.go
  vendor/github.com/hashicorp/terraform/plans/action_string.go
  vendor/github.com/hashicorp/terraform/states/eachmode_string.go
  vendor/github.com/hashicorp/terraform/states/objectstatus_string.go
  vendor/github.com/hashicorp/terraform/states/statefile/write.go
  vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
  vendor/github.com/hashicorp/terraform/terraform/eval_state_upgrade.go
  vendor/github.com/hashicorp/terraform/terraform/graphtype_string.go
  vendor/github.com/hashicorp/terraform/terraform/instancetype_string.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_apply_instance.go
  vendor/github.com/hashicorp/terraform/terraform/provider_mock.go
  vendor/github.com/hashicorp/terraform/terraform/valuesourcetype_string.go
  vendor/github.com/hashicorp/terraform/terraform/walkoperation_string.go
  vendor/github.com/hashicorp/terraform/tfdiags/severity_string.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/regexp.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/sequence.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#59 r/certificate: get certificate from CA if missing in state
  acme/resource_acme_certificate.go
  go.mod
  go.sum
  vendor/github.com/go-acme/lego/certificate/certificates.go
  vendor/modules.txt
Labels: dependencies, size/M

#60 r/certificate: use partial mode during certificate renewals
  acme/resource_acme_certificate.go
Labels: size/XS
