Repository vancluever/terraform-provider-acme, pull requests merged in 2019-02, with the labels that each got.

#20 Documentation update
  website/docs/dns_providers/route53.html.markdown
Labels: documentation, size/XS

#18 [WIP] Upgrade to lego@v2
  acme/acme_migrations.go
  acme/acme_migrations_test.go
  acme/acme_structure.go
  acme/acme_structure_test.go
  acme/resource_acme_certificate.go
  acme/resource_acme_certificate_test.go
  acme/resource_acme_registration.go
  acme/resource_acme_registration_test.go
  go.mod
  go.sum
  website/docs/r/certificate.html.markdown
Labels: documentation, size/XL

#25 r/certificate: Allow for recursive nameservers to be overridden
  acme/acme_structure.go
  acme/resource_acme_certificate_test.go
  acme/test_forwarder_test.go
  go.mod
  website/docs/r/certificate.html.markdown
Labels: documentation, size/L

#26 r/certificate: Add PKCS12 export field
  acme/acme_structure.go
  acme/resource_acme_certificate_test.go
  go.mod
  go.sum
  website/docs/r/certificate.html.markdown
Labels: documentation, size/M

#28 r/certificate: No partial, dns_challenge is list, no longer ForceNew
  acme/acme_migrations.go
  acme/acme_migrations_test.go
  acme/acme_structure.go
  acme/resource_acme_certificate.go
Labels: size/M
