Repository vancluever/terraform-provider-acme, pull requests merged in 2019-03, with the labels that each got.

#34 changed p12 cert to be padded
  acme/acme_structure.go
  acme/acme_structure_test.go
  acme/resource_acme_certificate_test.go
  website/docs/r/certificate.html.markdown
Labels: documentation, size/M

#37 Generate new p12 certificate when password is changed
  acme/acme_structure.go
  acme/resource_acme_certificate.go
  acme/resource_acme_certificate_test.go
Labels: size/M

#39 docs/r/certificate: certificate_p12 password is configurable
  website/docs/r/certificate.html.markdown
Labels: documentation, size/XS
